/*
   INFO: THE `USECALENDAR` CUSTOM HOOK IS RESPONSIBLE FOR MANAGING CALENDAR DATA AND STATE.
   IT FACILITATES THE RETRIEVAL, MANAGEMENT, AND UPDATING OF CALENDARS FOR THE APPLICATION.

   INFO: KEY FEATURES:
   - FETCHING CALENDARS FROM THE API.
   - HANDLING LOCAL STATE FOR THE CALENDAR DATA.
   - FUNCTIONS TO ADD, UPDATE, AND DELETE CALENDARS.
   - ERROR HANDLING FOR NETWORK REQUESTS.
   - ENSURING DATA SYNCHRONIZATION WITH THE BACKEND.

   WARN: NETWORK ERRORS AND API FAILURES SHOULD BE HANDLED TO PROVIDE A SMOOTH USER EXPERIENCE.
   WARN: AVOID LARGE STATE UPDATES TO PREVENT PERFORMANCE ISSUES.

   TODO: ADD FUNCTIONALITY FOR SHARING CALENDARS WITH OTHER USERS.
   TODO: IMPLEMENT ADDITIONAL FEATURES FOR CALENDAR COLOR CUSTOMIZATION.
   TODO: OPTIMIZE DATA FETCHING TO REDUCE LOAD TIMES.

   USAGE:
      CONST { CALENDARS, ADDCALENDAR, UPDATECALENDAR, DELETECALENDAR } = USECALENDAR();

   DEPENDENCIES:
   - REACT FOR MANAGING COMPONENT STATE.
   - TANSTACK QUERY FOR ASYNCHRONOUS DATA OPERATIONS.
*/
